package AnalisiSemanticoSQL;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luise
 */
public class JFAnalizadorSemantico extends javax.swing.JFrame {

    /**
     * Creates new form JFAnalizadorSemantico
     */
    public JFAnalizadorSemantico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRutaSQL = new javax.swing.JTextField();
        btnExaminarFlex = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnAnalizar = new javax.swing.JButton();
        txtRutaFlex = new javax.swing.JTextField();
        txtRutaCup = new javax.swing.JTextField();
        btnExaminarCup = new javax.swing.JButton();
        btnExaminarSQL = new javax.swing.JButton();
        btnGenerarFlex = new javax.swing.JButton();
        btnGenerarCup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRutaSQL.setEditable(false);

        btnExaminarFlex.setText("Seleccionar .flex");
        btnExaminarFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarFlexActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        txtRutaFlex.setEditable(false);
        txtRutaFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaFlexActionPerformed(evt);
            }
        });

        txtRutaCup.setEditable(false);

        btnExaminarCup.setText("Seleccionar .cup");
        btnExaminarCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarCupActionPerformed(evt);
            }
        });

        btnExaminarSQL.setText("Examinar");
        btnExaminarSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarSQLActionPerformed(evt);
            }
        });

        btnGenerarFlex.setText("Generar léxico");
        btnGenerarFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFlexActionPerformed(evt);
            }
        });

        btnGenerarCup.setText("Generar sintáctico");
        btnGenerarCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRutaCup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(txtRutaFlex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRutaSQL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExaminarCup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(btnExaminarSQL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExaminarFlex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarFlex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarCup, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExaminarFlex)
                    .addComponent(txtRutaFlex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarFlex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarCup)
                    .addComponent(btnGenerarCup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAnalizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRutaSQL)
                        .addComponent(btnExaminarSQL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaFlexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaFlexActionPerformed
    
    String rutaSQL;
    private void btnExaminarSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarSQLActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".sql", "sql");
        File fichero = null;        
        dialogo.setFileFilter(filtro);
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            fichero = dialogo.getSelectedFile();
            rutaSQL = fichero.getPath();
            txtRutaSQL.setText(rutaSQL);
        }
    }//GEN-LAST:event_btnExaminarSQLActionPerformed

    String rutaFlex;
    private void btnExaminarFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarFlexActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".flex", "Flex");
        File fichero = null;        
        dialogo.setFileFilter(filtro);
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            fichero = dialogo.getSelectedFile();
            rutaFlex = fichero.getPath();
            txtRutaFlex.setText(rutaFlex);
        }
    }//GEN-LAST:event_btnExaminarFlexActionPerformed

    String rutaCup;
    private void btnExaminarCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarCupActionPerformed
        // TODO add your handling code here:
        /*JFileChooser dialogo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".cup", "Cup");
        File fichero = null;        
        dialogo.setFileFilter(filtro);
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            fichero = dialogo.getSelectedFile();
            rutaCup = fichero.getPath();
            txtRutaCup.setText(rutaCup);
        }*/        
        rutaCup = "src/AnalisiSemanticoSQL/Sintax.cup";
    }//GEN-LAST:event_btnExaminarCupActionPerformed

    private void btnGenerarFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFlexActionPerformed
        // TODO add your handling code here:
        try {
            File archivo;
            archivo = new File(rutaFlex);
            JFlex.Main.generate(archivo);
        } catch (Exception e) {
            
        }        
    }//GEN-LAST:event_btnGenerarFlexActionPerformed

    private void btnGenerarCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCupActionPerformed
        // TODO add your handling code here:
        try {
            String[] rutaS = {"-parser", "Sintax", rutaCup};
            java_cup.Main.main(rutaS);
            
            Path rutaSym = Paths.get("src/AnalisiSemanticoSQL/sym.java");

            if(Files.exists(rutaSym)){

                Files.delete(rutaSym);

            }

            Files.move(

                    Paths.get("sym.java"), 

                    Paths.get("src/AnalisiSemanticoSQL/sym.java")

            );

            Path rutaSintax = Paths.get("src/AnalisiSemanticoSQL/Sintax.java");

            if(Files.exists(rutaSintax)){

                Files.delete(rutaSintax);

            }

            Files.move(

                    Paths.get("Sintax.java"), 

                    Paths.get("src/AnalisiSemanticoSQL/Sintax.java")

            );
        } catch (Exception e) {
            
        }        
    }//GEN-LAST:event_btnGenerarCupActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        Reader lector;

            String errors = "";

            try {
                lector = new BufferedReader(new FileReader(rutaSQL));
                Sintax s = new Sintax(new LexerCup(lector));
                try {
                    s.parse();
                    errors = s.obtenerErrores();
                    if(errors.length() > 0){
                        txtResultado.setText(s.obtenerErrores());
                    }
                    else{
                        txtResultado.setText("Analisis sintáctico exitoso \n");                        
                    }
                    
                    txtResultado.append("\n");
                    
                    if(TablaSimbolos.getErrores() == ""){
                        txtResultado.append("Análisis semántico exitoso \n");
                    }
                    else{
                        txtResultado.append(TablaSimbolos.getErrores());
                    }                    
                } catch (Exception ex) {
                    Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(Level.SEVERE, null, ex);
            }
            File archivoSalida=new File("tablaSimbolos.out");
                    PrintWriter escribir=null;
        try {
            escribir=new PrintWriter(archivoSalida);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(Level.SEVERE, null, ex);
        }
                    escribir.print(TablaSimbolos.EscribirArchivo());
                    escribir.close();
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAnalizadorSemantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAnalizadorSemantico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnExaminarCup;
    private javax.swing.JButton btnExaminarFlex;
    private javax.swing.JButton btnExaminarSQL;
    private javax.swing.JButton btnGenerarCup;
    private javax.swing.JButton btnGenerarFlex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtRutaCup;
    private javax.swing.JTextField txtRutaFlex;
    private javax.swing.JTextField txtRutaSQL;
    // End of variables declaration//GEN-END:variables
}
